<center><img style="float: center; width:90%" src="https://raw.githubusercontent.com/Jeshua-Romero-Guadarrama/CienciaDatosPython/main/images/JeshuaNomics.png">
</center><br>

<script src="https://kit.fontawesome.com/37a97f957d.js" crossorigin="anonymous"></script>

<center><a href="https://www.datascience.jeshuanomics.com/" target="blank" style="font-size:20px;">
Introducción a la Ciencia de Datos para Economistas en Python
</a></center>

<center><a href="https://www.jeshuanomics.com/" target="blank" style="font-size:20px;">
Publicado por Jeshua Romero Guadarrama en colaboración con JeshuaNomics
</a></center>
    
<center><a href="https://www.jeshuanomics.com/" target="blank">
____________________________________________________________________________________________________
</a></center><br>

<center>
<a href="https://github.com/JeshuaNomics"><i class="fa fa-github" aria-hidden="true"></i><span class="label"></span> GitHub  </a>
<a href="https://www.facebook.com/JeshuaNomics/"><i class="fa fa-facebook" aria-hidden="true"></i><span class="label"></span> Facebook  </a>
<a href="https://twitter.com/JeshuaNomics"><i class="fa fa-twitter" aria-hidden="true"></i><span class="label"></span> Twitter  </a>
<a href="https://www.linkedin.com/in/jeshua-romero-guadarrama/"><i class="fa fa-linkedin" aria-hidden="true"></i><span class="label"></span> Linkedin  </a>
<a href="https://vk.com/jeshuanomics"><i class="fa fa-vk" aria-hidden="true"></i><span class="label"></span> Vkontakte  </a>
<a href="https://jeshuanomics.tumblr.com/"><i class="fa fa-tumblr" aria-hidden="true"></i><span class="label"></span> Tumblr  </a>
<a href="https://www.youtube.com/channel/UCY7f84mJGvMN7TF7XI4-Jgg?view_as=subscriber/"><i class="fa fa-youtube-play" aria-hidden="true"></i><span class="label"></span> YouTube  </a>
<a href="https://www.instagram.com/JeshuaNomics/"><i class="fa fa-instagram" aria-hidden="true"></i><span class="label"></span> Instagram  </a>
<a href="https://www.datascience.jeshuanomics.com/"><i class="fa fa-check" aria-hidden="true"></i><span class="label"></span> DataScience </a>
</center><br><br>

# Using arrays and scalars

In [14]:
import numpy as np



In [15]:
5/2

2.5

In [16]:
#Takes care of floats
from __future__ import division

In [4]:
# Create array
arr1 = np.array([[1,2,3],[8,9,10]])

#Show
arr1


array([[ 1,  2,  3],
       [ 8,  9, 10]])

In [5]:
#Multiplying Arrays
arr1*arr1

array([[  1,   4,   9],
       [ 64,  81, 100]])

In [6]:
#Subtraction
arr1-arr1

array([[0, 0, 0],
       [0, 0, 0]])

In [10]:
#Arithmetic operations with scalars on array
1 / arr1

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.125     ,  0.11111111,  0.1       ]])

In [18]:
#Exponential operation
arr1 ** 3

array([[   1,    8,   27],
       [ 512,  729, 1000]])