<center><img style="float: center; width:90%" src="https://raw.githubusercontent.com/Jeshua-Romero-Guadarrama/CienciaDatosPython/main/images/JeshuaNomics.png">
</center><br>

<script src="https://kit.fontawesome.com/37a97f957d.js" crossorigin="anonymous"></script>

<center><a href="https://www.datascience.jeshuanomics.com/" target="blank" style="font-size:20px;">
Introducción a la Ciencia de Datos para Economistas en Python
</a></center>

<center><a href="https://www.jeshuanomics.com/" target="blank" style="font-size:20px;">
Publicado por Jeshua Romero Guadarrama en colaboración con JeshuaNomics
</a></center>
    
<center><a href="https://www.jeshuanomics.com/" target="blank">
____________________________________________________________________________________________________
</a></center><br>

<center>
<a href="https://github.com/JeshuaNomics"><i class="fa fa-github" aria-hidden="true"></i><span class="label"></span> GitHub  </a>
<a href="https://www.facebook.com/JeshuaNomics/"><i class="fa fa-facebook" aria-hidden="true"></i><span class="label"></span> Facebook  </a>
<a href="https://twitter.com/JeshuaNomics"><i class="fa fa-twitter" aria-hidden="true"></i><span class="label"></span> Twitter  </a>
<a href="https://www.linkedin.com/in/jeshua-romero-guadarrama/"><i class="fa fa-linkedin" aria-hidden="true"></i><span class="label"></span> Linkedin  </a>
<a href="https://vk.com/jeshuanomics"><i class="fa fa-vk" aria-hidden="true"></i><span class="label"></span> Vkontakte  </a>
<a href="https://jeshuanomics.tumblr.com/"><i class="fa fa-tumblr" aria-hidden="true"></i><span class="label"></span> Tumblr  </a>
<a href="https://www.youtube.com/channel/UCY7f84mJGvMN7TF7XI4-Jgg?view_as=subscriber/"><i class="fa fa-youtube-play" aria-hidden="true"></i><span class="label"></span> YouTube  </a>
<a href="https://www.instagram.com/JeshuaNomics/"><i class="fa fa-instagram" aria-hidden="true"></i><span class="label"></span> Instagram  </a>
<a href="https://www.datascience.jeshuanomics.com/"><i class="fa fa-check" aria-hidden="true"></i><span class="label"></span> DataScience </a>
</center><br><br>

# Array Input and Output

In [1]:
import numpy as np



In [2]:
#Create an array
arr = np.arange(5)

In [3]:
#Saving array on disk in binary format (file extension .npy)
np.save('my_array',arr)

In [4]:
#Change arr
arr = np.arange(10)
#Show
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
#Lets see the original saved copy
np.load('my_array.npy')

array([0, 1, 2, 3, 4])

In [8]:
#Saving multiple arrays into a zip file
np.savez('two_arrays.npz',x=arr,y=arr)

In [14]:
#Now loading multiple arrays
archive_array = np.load('two_arrays.npz')

#Show
archive_array['x']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
#Now lets remove them from the memory
rm my_array.npy
rm two_arrays.npz

SyntaxError: invalid syntax (<ipython-input-16-7d53e496e836>, line 2)

In [25]:
#Now saving and loading text files

arr = np.array([[1,2,3],[4,5,6]])
np.savetxt('my_test_text.txt',arr,delimiter=',')

In [26]:
arr = np.loadtxt('my_test_text.txt',delimiter = ',')
arr


array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])