<center><img style="float: center; width:90%" src="https://raw.githubusercontent.com/Jeshua-Romero-Guadarrama/CienciaDatosPython/main/images/JeshuaNomics.png">
</center><br>

<script src="https://kit.fontawesome.com/37a97f957d.js" crossorigin="anonymous"></script>

<center><a href="https://www.datascience.jeshuanomics.com/" target="blank" style="font-size:20px;">
Introducción a la Ciencia de Datos para Economistas en Python
</a></center>

<center><a href="https://www.jeshuanomics.com/" target="blank" style="font-size:20px;">
Publicado por Jeshua Romero Guadarrama en colaboración con JeshuaNomics
</a></center>
    
<center><a href="https://www.jeshuanomics.com/" target="blank">
____________________________________________________________________________________________________
</a></center><br>

<center>
<a href="https://github.com/JeshuaNomics"><i class="fa fa-github" aria-hidden="true"></i><span class="label"></span> GitHub  </a>
<a href="https://www.facebook.com/JeshuaNomics/"><i class="fa fa-facebook" aria-hidden="true"></i><span class="label"></span> Facebook  </a>
<a href="https://twitter.com/JeshuaNomics"><i class="fa fa-twitter" aria-hidden="true"></i><span class="label"></span> Twitter  </a>
<a href="https://www.linkedin.com/in/jeshua-romero-guadarrama/"><i class="fa fa-linkedin" aria-hidden="true"></i><span class="label"></span> Linkedin  </a>
<a href="https://vk.com/jeshuanomics"><i class="fa fa-vk" aria-hidden="true"></i><span class="label"></span> Vkontakte  </a>
<a href="https://jeshuanomics.tumblr.com/"><i class="fa fa-tumblr" aria-hidden="true"></i><span class="label"></span> Tumblr  </a>
<a href="https://www.youtube.com/channel/UCY7f84mJGvMN7TF7XI4-Jgg?view_as=subscriber/"><i class="fa fa-youtube-play" aria-hidden="true"></i><span class="label"></span> YouTube  </a>
<a href="https://www.instagram.com/JeshuaNomics/"><i class="fa fa-instagram" aria-hidden="true"></i><span class="label"></span> Instagram  </a>
<a href="https://www.datascience.jeshuanomics.com/"><i class="fa fa-check" aria-hidden="true"></i><span class="label"></span> DataScience </a>
</center><br><br>

# Permutation

In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [7]:
# WE can randomly reorder (permutate) a Series, or the rows in a DataFrame

#Let's take a look
dframe = DataFrame(np.arange(4 * 4).reshape((4, 4)))

#Create an array with a random perumation of 0,1,2,3
blender = np.random.permutation(4)

blender

array([3, 0, 1, 2])

In [8]:
dframe

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [5]:
# Now permutate the dframe based on the blender
dframe.take(blender)

0   1   2   3
0   0   1   2   3
2   8   9  10  11
3  12  13  14  15
1   4   5   6   7

In [2]:
# Now what if we want permuations WITH replacement

In [13]:
# Let imagine a box with 3 marbles in it: labeled 1, 2, and 3
box = np.array([1,2,3])

# Now lets create a random permuation WITH replacement using randint
shaker = np.random.randint(0, len(box), size=10)

In [14]:
# Let's check teh box "shaker"
shaker

array([2, 0, 1, 2, 1, 0, 0, 2, 0, 2])

In [15]:
#Now lets grab form the box
hand_grabs = box.take(shaker)

#show
hand_grabs

array([3, 1, 2, 3, 2, 1, 1, 3, 1, 3])

Congratulations! We're all done with this Section.
Up next: Working with Data Part 3 !!!